# Disable Jekyll processing
plugins: []
markdown: kramdown
highlighter: none

# Include all Unity WebGL files
include:
  - "Build/"
  - "TemplateData/"
  - "*.wasm"
  - "*.data"
  - "*.js"

# Ensure proper serving
defaults:
  - scope:
      path: "Build"
    values:
      layout: null
